RQ-1002 판매자 도메인 및 회원가입/로그인 API 구현
dnd2dnd/spring-concurrency-issue pull request #5
Opened 2024-05-04 07:45 UTC by Eom-Ye-rim

## 📄 Summary
> 판매자 도메인 및 회원가입/로그인 API 구현
## 🙋🏻 More
> 일반 회원(소비자)과 판매자 로그인 과정에서 겹치는 로직과 컬럼들은 따로 빼면 좋을 것 같아요 (추후 같이 회의하면서 논의해봐요)
> 판매자 도메인에서 사업자 번호 변수명을 축약하는게 나을까요?
> 업체 주소도 포맷 맞추는게 낫겠죠?

2024-05-04 07:47 UTC, Eom-Ye-rim commented on src/main/java/com/project/seller/SellerConstant.java
✅ TODO 부분은 string으로 하기로 논의 끝

2024-05-05 00:42 UTC, dnd2dnd requested changes

2024-05-05 00:42 UTC, dnd2dnd commented on src/main/java/com/project/seller/domain/Seller.java
> + * */
이렇게 적는 거 좋은 것 같네요

2024-05-05 00:42 UTC, dnd2dnd commented on src/main/java/com/project/auth/service/AuthService.java
> +	//TODO entity만 다르고 같은 로직이라 뭔가 코드 중복인 느낌이네요.. 어떻게 방법이 없을까요!?
하나의 로직에서 해결할 수 있게 바꿔야겠네요..

2024-05-05 03:45 UTC, dnd2dnd requested changes

2024-05-05 03:45 UTC, dnd2dnd commented on src/main/java/com/project/auth/service/AuthService.java
> +	}
toSeller는 도메인에 넣어도 될 것 같아요

2024-05-07 09:25 UTC, dnd2dnd commented on src/main/java/com/project/auth/domain/BaseAuth.java
> +		return this.email.getEmail();
this. 빼도 될 것 같아요

2024-05-07 09:25 UTC, dnd2dnd commented on src/main/java/com/project/auth/service/AuthService.java
> +public interface AuthService {
메소드가 추가안될예정이라면 (LoginService or SigninService) 하는거 어떻게 생각하시나요

2024-05-07 09:25 UTC, dnd2dnd commented on src/main/java/com/project/member/service/MemberService.java
> +
@Override 메소드를 맨 위로 올리는건 어떻게 생각하시나요??
이런 것도 뭔가 순서 양식? 그런게 있을 것 같네요

2024-05-07 09:25 UTC, dnd2dnd commented on src/main/java/com/project/seller/controller/SellerController.java
>  	@PostMapping("sign-up")
엔터... ㅎ

2024-05-07 09:25 UTC, dnd2dnd commented on src/main/java/com/project/seller/service/SellerService.java
> +	public TokenResponse signIn(SignInRequest signInRequest) {
find만 하는 메소드이니 @Transactional(readonly = true)를 붙이는게 어떨까요

2024-05-08 10:19 UTC, dnd2dnd approved these changes

2024-05-08 10:20 UTC, merged